pipeline:
  name: test-astrobee
  identifier: testastrobee
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: spahujarepos
        repoName: go-ethereum
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: BuildAndTest_astrobee
        identifier: BuildAndTest_astrobee
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: RunStep
                  identifier: RunStep
                  spec:
                    shell: Bash
                    command: |-
                      sudo add-apt-repository ppa:longsleep/golang-backports
                      sudo apt update
                      sudo apt install golang-go

                      go clean -modcache
                      go mod tidy

                      make all
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        strategy:
          parallelism: 1
