pipeline:
  name: test-astrobee
  identifier: testastrobee
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: spahujarepos
        repoName: astrobee
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: BuildAndTest_astrobee
        identifier: BuildAndTest_astrobee
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: RunStep
                  identifier: RunStep
                  spec:
                    shell: Bash
                    command: |-
                      chmod +x scripts/docker/build.sh
                      RUN apt-get update && apt-get install -y \
                          ros-noetic-ar-track-alvar-msgs
                          
                      ./scripts/docker/build.sh
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        strategy:
          parallelism: 1
