pipeline:
  name: test-astrobee
  identifier: testastrobee
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: astrobee
        build: <+input>
  stages:
    - stage:
        name: BuildAndTest_astrobee
        identifier: BuildAndTest_astrobee
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: RunStep
                  identifier: RunStep
                  spec:
                    shell: Bash
                    command: |-
                      chmod 777 ./scripts/docker/build.sh
                      ./scripts/docker/build.sh --bionic --remote astrobee test_astrobee
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        strategy:
          parallelism: 1
