pipeline:
  name: test-astrobee
  identifier: testastrobee
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: astrobee
        build: <+input>
  stages:
    - stage:
        name: BuildAndTest_astrobee
        identifier: BuildAndTest_astrobee
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: aws-linux-amd64-harsh
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: RunStep
                  identifier: RunStep
                  spec:
                    shell: Bash
                    command: |-
                      chmod 777 ./scripts/docker/build.sh
                      ./scripts/docker/build.sh --bionic --remote astrobee test_astrobee
                  failureStrategies: []
        strategy:
          parallelism: 1
